#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
typedef union {
    long long int i;
    double f;
} int_or_float;
int_or_float tape[30000], *ref_stack[30000], *ptr = tape, reg, tmp;
unsigned int ref_stack_ptr = 0;
void (*funs[10000])(void);
int main() {
	reg.i = 0;
	ptr += 9;
	reg.i = (long long int)ptr;
	ptr -= 9;
	*ptr = reg;
	reg = *ptr;
	ptr += 2;
	*ptr = reg;
	ptr -= 2;
	void f0() {
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		ptr += 1;
		reg.i = (long long int)ptr;
		ptr -= 1;
		ptr = ref_stack[--ref_stack_ptr];
		*ptr = reg;
		ptr += 2;
		reg = *ptr;
		ptr -= 2;
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		*ptr = reg;
		ptr = ref_stack[--ref_stack_ptr];
		reg = *ptr;
		ptr += 2;
		*ptr = reg;
		ptr -= 2;
		ptr += 2;
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		ptr -= 1;
		reg = *ptr;
		ptr += 1;
		ptr = ref_stack[--ref_stack_ptr];
		ptr -= 2;
		ptr += 3;
		*ptr = reg;
		ptr -= 3;
		reg.i = 10;
		ptr += 4;
		*ptr = reg;
		ptr -= 4;
		ptr += 4;
		reg = *ptr;
		ptr -= 4;
		ptr += 1;
		*ptr = reg;
		ptr -= 1;
		ptr += 3;
		reg = *ptr;
		ptr -= 3;
		ptr += 4;
		*ptr = reg;
		ptr -= 4;
		ptr += 3;
		reg = *ptr;
		ptr -= 3;
		ptr += 1;
		reg.i /= ptr->i;
		ptr -= 1;
		ptr += 3;
		*ptr = reg;
		ptr -= 3;
		ptr += 4;
		reg = *ptr;
		ptr -= 4;
		ptr += 1;
		reg.i %= ptr->i;
		ptr -= 1;
		ptr += 4;
		*ptr = reg;
		ptr -= 4;
		ptr += 3;
		reg = *ptr;
		ptr -= 3;
		if (reg.i) {
			ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
			ptr += 1;
			reg.i = (long long int)ptr;
			ptr -= 1;
			ptr = ref_stack[--ref_stack_ptr];
			*ptr = reg;
			ptr += 4;
			reg = *ptr;
			ptr -= 4;
			ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
			*ptr = reg;
			ptr = ref_stack[--ref_stack_ptr];
			ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
			ptr += 1;
			reg.i = (long long int)ptr;
			ptr -= 1;
			ptr = ref_stack[--ref_stack_ptr];
			*ptr = reg;
			ptr += 3;
			reg = *ptr;
			ptr -= 3;
			ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
			*ptr = reg;
			ptr = ref_stack[--ref_stack_ptr];
			reg.i = 0;
			funs[reg.i]();
			ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
			ptr -= 1;
			reg.i = (long long int)ptr;
			ptr += 1;
			ptr = ref_stack[--ref_stack_ptr];
			*ptr = reg;
			ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
			reg = *ptr;
			ptr = ref_stack[--ref_stack_ptr];
			ptr += 4;
			*ptr = reg;
			ptr -= 4;
			ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
			ptr -= 1;
			reg.i = (long long int)ptr;
			ptr += 1;
			ptr = ref_stack[--ref_stack_ptr];
			*ptr = reg;
		}
		reg.i = 48;
		ptr += 3;
		*ptr = reg;
		ptr -= 3;
		ptr += 4;
		reg = *ptr;
		ptr -= 4;
		ptr += 3;
		reg.i += ptr->i;
		ptr -= 3;
		ptr += 4;
		*ptr = reg;
		ptr -= 4;
		ptr += 4;
		reg = *ptr;
		ptr -= 4;
		putchar(reg.i);
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		reg = *ptr;
		ptr = ref_stack[--ref_stack_ptr];
		ptr += 2;
		*ptr = reg;
		ptr -= 2;
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		ptr -= 1;
		reg.i = (long long int)ptr;
		ptr += 1;
		ptr = ref_stack[--ref_stack_ptr];
		*ptr = reg;
	} funs[0] = f0;
	reg.i = 1000000;
	ptr += 8;
	*ptr = reg;
	ptr -= 8;
	ptr += 8;
	reg = *ptr;
	ptr -= 8;
	while (reg.i) {
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		ptr += 1;
		reg.i = (long long int)ptr;
		ptr -= 1;
		ptr = ref_stack[--ref_stack_ptr];
		*ptr = reg;
		ptr += 8;
		reg = *ptr;
		ptr -= 8;
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		*ptr = reg;
		ptr = ref_stack[--ref_stack_ptr];
		reg.i = 0;
		funs[reg.i]();
		ref_stack[ref_stack_ptr++] = ptr; ptr = (int_or_float*)ptr->i;
		ptr -= 1;
		reg.i = (long long int)ptr;
		ptr += 1;
		ptr = ref_stack[--ref_stack_ptr];
		*ptr = reg;
		reg.i = 10;
		ptr += 7;
		*ptr = reg;
		ptr -= 7;
		ptr += 7;
		reg = *ptr;
		ptr -= 7;
		putchar(reg.i);
		ptr += 8;
		reg = *ptr;
		reg.i--;
		*ptr = reg;
		ptr -= 8;
		ptr += 8;
		reg = *ptr;
		ptr -= 8;
	}
	return 0;
}
